include: package:lint/analysis_options.yaml

analyzer:
  exclude:

linter:
  rules:
    use_build_context_synchronously: false
    avoid_dynamic_calls: false
    use_setters_to_change_properties: false
    cast_nullable_to_non_nullable: false
    depend_on_referenced_packages: false
