name: quizlet
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.11
  cupertino_icons: ^1.0.2
  file_picker: ^4.5.1
  firebase_auth: ^3.3.12
  firebase_core: ^1.14.0
  firebase_storage: ^10.2.15
  flutter:
    sdk: flutter
  google_ml_kit: ^0.11.0
  google_sign_in: ^5.3.0
  image_picker: ^0.8.5+3
  lint: ^1.8.2
  loading_indicator: ^3.1.0
  modal_bottom_sheet: ^2.0.1
  path: ^1.8.1
  provider: ^6.0.2 #to be removed
  responsive_framework: ^0.1.9

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSans-Bold.ttf
        - asset: fonts/GoogleSans-BoldItalic.ttf
        - asset: fonts/GoogleSans-Italic.ttf
        - asset: fonts/GoogleSans-Medium.ttf
        - asset: fonts/GoogleSans-MediumItalic.ttf
        - asset: fonts/GoogleSans-Regular.ttf
