name: quizlet
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  carousel_slider: ^4.0.0
  provider: ^6.0.2
  google_sign_in: ^5.3.0
  firebase_core: ^1.14.0
  cloud_firestore: ^3.1.11
  firebase_auth: ^3.3.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSans-Bold.ttf
        - asset: fonts/GoogleSans-BoldItalic.ttf
        - asset: fonts/GoogleSans-Italic.ttf
        - asset: fonts/GoogleSans-Medium.ttf
        - asset: fonts/GoogleSans-MediumItalic.ttf
        - asset: fonts/GoogleSans-Regular.ttf
