// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3uhDEs0B8V64UbxmxgrV2rtkLW-6h_bc',
    appId: '1:627528502360:web:205f9b6f1c6f72cf610e2d',
    messagingSenderId: '627528502360',
    projectId: 'quizzy-64099',
    authDomain: 'quizzy-64099.firebaseapp.com',
    storageBucket: 'quizzy-64099.appspot.com',
    measurementId: 'G-4NXHD8350Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATd5FPXRABGrV20r7jn-K1O6Ue9lXUD8c',
    appId: '1:627528502360:android:daf0f361d24eefb2610e2d',
    messagingSenderId: '627528502360',
    projectId: 'quizzy-64099',
    storageBucket: 'quizzy-64099.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVRlTapDOvMjN5f2_uV_LRBsE-65DNZLU',
    appId: '1:627528502360:ios:55e0888b592d7f7c610e2d',
    messagingSenderId: '627528502360',
    projectId: 'quizzy-64099',
    storageBucket: 'quizzy-64099.appspot.com',
    iosClientId: '627528502360-285ra0k24e1ep6r765q0oncojqbjuohe.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizlet',
  );
}
